In [ ]:

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from typing import dataclass_transform
data = pd.read_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/UNSW_NB15_training-set.csv')
data

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.090200,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.000300,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.005100,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.660800,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.002500,...,1,3,0,0,0,2,3,0,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82327,82328,0.000005,udp,-,INT,2,0,104,0,200000.005100,...,1,2,0,0,0,2,1,0,Normal,0
82328,82329,1.106101,tcp,-,FIN,20,8,18062,354,24.410067,...,1,1,0,0,0,3,2,0,Normal,0
82329,82330,0.000000,arp,-,INT,1,0,46,0,0.000000,...,1,1,0,0,0,1,1,1,Normal,0
82330,82331,0.000000,arp,-,INT,1,0,46,0,0.000000,...,1,1,0,0,0,1,1,1,Normal,0
82331,82332,0.000009,udp,-,INT,2,0,104,0,111111.107200,...,1,1,0,0,0,1,1,0,Normal,0

In [ ]:
data.columns

Index(['id', 'dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='object')

In [ ]:
data.isnull().sum()

id                   0
dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64

In [ ]:
data = data.drop(['id'], axis=1)

In [ ]:
data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [ ]:
encoder = LabelEncoder()

data['proto'] = encoder.fit_transform(data['proto'])
data['service'] = encoder.fit_transform(data['service'])
data['state'] = encoder.fit_transform(data['state'])

In [ ]:
data.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,117,0,4,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,117,0,4,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,117,0,4,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,117,0,4,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,117,0,4,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [ ]:
pd.crosstab(data['label'], data['attack_cat'])

attack_cat,Analysis,Backdoor,DoS,Exploits,Fuzzers,Generic,Normal,Reconnaissance,Shellcode,Worms
label,,,,,,,,,,
0,0,0,0,0,0,0,37000,0,0,0
1,677,583,4089,11132,6062,18871,0,3496,378,44

In [ ]:
labels = data[['label', 'attack_cat']]

data = data.drop(['label', 'attack_cat'], axis=1)

In [ ]:
X = data.select_dtypes(include=['int64','float64'])
X.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports
0,0.000011,117,0,4,2,0,496,0,90909.0902,254,...,1,1,1,2,0,0,0,1,2,0
1,0.000008,117,0,4,2,0,1762,0,125000.0003,254,...,1,1,1,2,0,0,0,1,2,0
2,0.000005,117,0,4,2,0,1068,0,200000.0051,254,...,1,1,1,3,0,0,0,1,3,0
3,0.000006,117,0,4,2,0,900,0,166666.6608,254,...,2,2,1,3,0,0,0,2,3,0
4,0.000010,117,0,4,2,0,2126,0,100000.0025,254,...,2,2,1,3,0,0,0,2,3,0

In [ ]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports
0,-0.213727,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.043684,-0.087369,0.057181,0.71944,...,-0.563660,-0.468312,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607
1,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.036308,-0.087369,0.286565,0.71944,...,-0.563660,-0.468312,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607
2,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.040351,-0.087369,0.791209,0.71944,...,-0.563660,-0.468312,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.640033,-0.554273,-0.10607
3,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.041330,-0.087369,0.566923,0.71944,...,-0.444868,-0.349115,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607
4,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.034187,-0.087369,0.118350,0.71944,...,-0.444868,-0.349115,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607

In [ ]:
X_scaled_df['label'] = labels['label'].values
X_scaled_df['attack_cat'] = labels['attack_cat'].values
X_scaled_df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label,attack_cat
0,-0.213727,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.043684,-0.087369,0.057181,0.71944,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607,0,Normal
1,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.036308,-0.087369,0.286565,0.71944,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607,0,Normal
2,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.040351,-0.087369,0.791209,0.71944,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.640033,-0.554273,-0.10607,0,Normal
3,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.041330,-0.087369,0.566923,0.71944,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607,0,Normal
4,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.034187,-0.087369,0.118350,0.71944,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607,0,Normal

In [ ]:
X_scaled_df.to_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/scaled_data.csv', index=False)

In [ ]:
features = pd.read_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/feature_data.csv')
original = pd.read_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/scaled_data.csv')

In [ ]:
features['new_label'] = original['label']
features['attack_cat'] = original['attack_cat']
features.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,label,total_packets,total_bytes,byte_ratio,packets_per_sec,bytes_per_sec,byte_diff,srv_diff,new_label,attack_cat
0,-0.213727,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.043684,-0.087369,0.057181,0.71944,...,-1.106883,-0.166929,-0.092206,-0.051105,-0.437896,-0.248618,0.031046,-0.172385,0,Normal
1,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.036308,-0.087369,0.286565,0.71944,...,-1.106883,-0.166929,-0.087017,-0.041421,-0.437897,-0.224496,0.036288,-0.172385,0,Normal
2,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.040351,-0.087369,0.791209,0.71944,...,-1.106883,-0.166929,-0.089862,-0.046729,-0.437897,-0.237720,0.033415,-0.171186,0,Normal
3,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.041330,-0.087369,0.566923,0.71944,...,-1.106883,-0.166929,-0.090550,-0.048014,-0.437897,-0.240921,0.032719,-0.171186,0,Normal
4,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.034187,-0.087369,0.118350,0.71944,...,-1.106883,-0.166929,-0.085525,-0.038636,-0.437897,-0.217560,0.037795,-0.171186,0,Normal

In [ ]:
features.to_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/final_data.csv', index=False)