In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
data = pd.read_csv('/content/drive/MyDrive/Network-Anomaly-Detection-Project/Dataset/scaled_data.csv')
data.head(10)

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label,attack_cat
0,-0.213727,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.043684,-0.087369,0.057181,0.719440,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607,0,Normal
1,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.036308,-0.087369,0.286565,0.719440,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.640033,-0.644190,-0.10607,0,Normal
2,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.040351,-0.087369,0.791209,0.719440,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.640033,-0.554273,-0.10607,0,Normal
3,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.041330,-0.087369,0.566923,0.719440,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607,0,Normal
4,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.034187,-0.087369,0.118350,0.719440,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.522990,-0.554273,-0.10607,0,Normal
5,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.042006,-0.087369,1.688355,0.719440,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.522990,-0.644190,-0.10607,0,Normal
6,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.035154,-0.087369,0.566923,0.719440,...,-0.450186,-0.477994,-0.090857,-0.090617,-0.203143,-0.522990,-0.644190,-0.10607,0,Normal
7,-0.213724,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.038510,-0.087369,-0.314202,0.719440,...,-0.450186,-0.390391,-0.090857,-0.090617,-0.203143,-0.640033,-0.554273,-0.10607,0,Normal
8,-0.213730,-5.545277,-0.674406,0.932695,-0.131922,-0.151816,-0.046305,-0.087369,-0.554509,-1.782709,...,-0.281135,-0.477994,-0.090857,-0.090617,-0.203143,-0.522990,-0.644190,9.42773,0,Normal
9,-0.213730,-5.545277,-0.674406,0.932695,-0.131922,-0.151816,-0.046305,-0.087369,-0.554509,-1.782709,...,-0.281135,-0.477994,-0.090857,-0.090617,-0.203143,-0.522990,-0.644190,9.42773,0,Normal

In [8]:
data['total_packets'] = data['spkts'] + data['dpkts']

data['total_bytes'] = data['sbytes'] + data['dbytes']

data['byte_ratio'] = data['sbytes'] / (data['dbytes'] + 1)

data['packets_per_sec'] = data['total_packets'] / (data['dur'] + 1)

data['bytes_per_sec'] = data['total_bytes'] / (data['dur'] + 1)

data['byte_diff'] = data['sbytes'] - data['dbytes']

data['srv_diff'] = data['ct_srv_src'] - data['ct_srv_dst']

In [9]:
data.head(10)

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,is_sm_ips_ports,label,attack_cat,total_packets,total_bytes,byte_ratio,packets_per_sec,bytes_per_sec,byte_diff,srv_diff
0,-0.213727,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.043684,-0.087369,0.057181,0.719440,...,-0.10607,0,Normal,-0.276272,-0.131052,-0.047866,-0.351369,-0.166675,0.043685,-0.036284
1,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.036308,-0.087369,0.286565,0.719440,...,-0.10607,0,Normal,-0.276272,-0.123676,-0.039784,-0.351369,-0.157295,0.051061,-0.036284
2,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.040351,-0.087369,0.791209,0.719440,...,-0.10607,0,Normal,-0.276272,-0.127720,-0.044214,-0.351369,-0.162437,0.047018,-0.036031
3,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.041330,-0.087369,0.566923,0.719440,...,-0.10607,0,Normal,-0.276272,-0.128699,-0.045286,-0.351369,-0.163682,0.046039,-0.036031
4,-0.213728,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.034187,-0.087369,0.118350,0.719440,...,-0.10607,0,Normal,-0.276272,-0.121556,-0.037460,-0.351369,-0.154598,0.053182,-0.036031
5,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.042006,-0.087369,1.688355,0.719440,...,-0.10607,0,Normal,-0.276272,-0.129374,-0.046027,-0.351369,-0.164542,0.045363,-0.036284
6,-0.213729,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.035154,-0.087369,0.566923,0.719440,...,-0.10607,0,Normal,-0.276272,-0.122523,-0.038520,-0.351369,-0.155828,0.052215,-0.036284
7,-0.213724,0.410563,-0.674406,0.932695,-0.124455,-0.151816,-0.038510,-0.087369,-0.314202,0.719440,...,-0.10607,0,Normal,-0.276272,-0.125879,-0.042197,-0.351367,-0.160095,0.048859,-0.036031
8,-0.213730,-5.545277,-0.674406,0.932695,-0.131922,-0.151816,-0.046305,-0.087369,-0.554509,-1.782709,...,9.42773,0,Normal,-0.283739,-0.133674,-0.050738,-0.360867,-0.170010,0.041063,-0.036284
9,-0.213730,-5.545277,-0.674406,0.932695,-0.131922,-0.151816,-0.046305,-0.087369,-0.554509,-1.782709,...,9.42773,0,Normal,-0.283739,-0.133674,-0.050738,-0.360867,-0.170010,0.041063,-0.036284

In [11]:
encoder = LabelEncoder()

for col in data.select_dtypes(include='object').columns:
    data[col] = encoder.fit_transform(data[col])

In [12]:
X = data.select_dtypes(include=['int64', 'float64'])

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

In [13]:
X_scaled_df.to_csv("feature_data.csv", index=False)